### ISSUE TITLE
باگ بودن

### ISSUE THREAD

**Issue by funwowserver** [ltiny/funwowserver#20]
-- Tracker :Spell<br />-- Spell ID : <br />-- Link : <br /><br /><br />http://s4.picofile.com/file/8174705984/wow_2015_03_03_11_34_30_27.mpg.html

پلیر " پالامستر" توی استان  می کنه فکر کنم اسپل "سوردش" هست همش اکتیو هست و نمی ذاره از استان خارج  شیم لطفا برسی کنین

**Comment by ltiny** [comment]
سلام

مشکل برطرف شد
