### ISSUE TITLE
Error (C)

### ISSUE THREAD

**Issue by funwowserver** [ltiny/funwowserver#26]
-- Realm : ShadowMourne 3.3.5a<br />-- Issues By : rezac<br />-- Tracker :General<br />-- Spell ID : Rrefresh<br />-- Link : <br /><br /><br />salam.aziz Vaghti (C) Mizanam Error mide Bazi va mindaze birun az bazi.Mikham Mount Biyaram Nemishe injuri.

**Comment by ltiny** [comment]
hi

you need user : 

Launcher : http://get.funwowserver.com/application/Funwowserver.exe

OR

Custom Patch6.mpq : http://get.funwowserver.com/patch/patch-6.mpq

OR

in Game Use Command : 

/console PlayerStatLeftDropDown Melee
/console PlayerStatRightDropDown Spell
/reload
