### ISSUE TITLE
Holy Shield

### ISSUE THREAD

**Issue by funwowserver** [ltiny/funwowserver#9]
-- Tracker :Spell<br />-- Spell ID : 20925<br />-- Link : <br /><br /><br />Holy Shield this levl must have 30% damage block but this levl when player us it 
we cant kill him or hit him or any damage to him paladin cant be killd and this levl must have 20sec coldown or 15 or ... but this levl have 8sec coldown

**Comment by ltiny** [comment]
Thank you

The problem was resolved
